# Generated by Django 5.0.6 on 2024-07-02 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_car_remove_customuser_id_customuser_user_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='CarModel',
        ),
    ]
