# Generated by Django 5.0.6 on 2024-07-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_car_carmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='car_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
