# Generated by Django 5.0.6 on 2024-07-02 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_carmodel_id_remove_customuser_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarModel',
        ),
    ]
