# Generated by Django 5.0.6 on 2024-07-02 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_carmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('Category', models.CharField(choices=[('SUV', 'SUV'), ('Prime', 'Prime'), ('Sedan', 'Sedan'), ('Electic Car', 'Electric Car')], max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('number_plate', models.CharField(max_length=10)),
                ('current_city', models.CharField(max_length=50)),
                ('rent_per_hour', models.IntegerField()),
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Rent_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carmodel')),
            ],
        ),
    ]
